project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - text: "R Series"
        menu:
        - text: "Episode 1"
          href: Episode1.html
        - text: "Episode 2"
          href: Episode2.html
        - text: "Episode 3"
          href: Episode3.html
      - text: "Now You See It"
        href: xxx.htlm
      - text: "Introduction to QGIS"
        href: introQGIS.htlm
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

